[package]
name = "IcarusDownloadManager"
version = "0.1.0"
edition = "2021"




# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
# rodio = "0.17.3"
# metadata = "0.1.8"