[package]
name = "icarus-dm"
version = "0.1.0"
edition = "2021"




# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.30" }
reqwest = { version = "0.12.4", features = ["json", "blocking"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
tokio = { version = "1.37", features = ["full"] }
# rodio = "0.17.3"
# metadata = "0.1.8"
