[package]
name = "icarus-dm"
version = "0.4.0"
edition = "2024"




# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.30" }
http = { version = "1.1.0" }
reqwest = { version = "0.12.4", features = ["json", "blocking", "multipart", "stream"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
tokio = { version = "1.37", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["codec"] }
