[package]
name = "icarus-dm"
version = "0.4.0"
edition = "2024"




# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.31" }
http = { version = "1.2.0" }
reqwest = { version = "0.12.12", features = ["json", "blocking", "multipart", "stream"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tokio = { version = "1.43", features = ["full"] }
tokio-util = { version = "0.7.13", features = ["codec"] }
icarus-models = { git = "ssh://git@gitlab.com/kdeng00/icarus-models.git", tag = "v0.1.1" }
