name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "icarus_v2_support" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust version
      run: rustup install 1.88.0 && rustup default 1.88.0

    - name: Debug secret
      run: echo "${{ secrets.MYREPO_TOKEN }}" | head -c 10 ; echo "..."
    
    - name: Build
      run: |
        mkdir -p ~/.ssh
        echo "$EXTREPO_KEY" > ~/.ssh/gitlab_deploy_key
        chmod 600 ~/.ssh/gitlab_deploy_key
        ssh-keyscan git.kundeng.us ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLl/OZiKVDxwnyvMxa+rjKvDpKqTxH1GWuGuDPLmENGQMbTVulajZWr9x8Q1cotoJiHZkt7DA5vczcjB/4lwgWA= >> ~/.ssh/known_hosts

        eval $(ssh-agent -s)
        ssh-add -v ~/.ssh/gitlab_deploy_key
        cargo build --release
      env:
        EXTREPO_KEY: ${{ secrets.MYREPO_TOKEN }}

    - name: Run tests
      run: cargo test --verbose
